### ISSUE TITLE
Issue with Multiple UPS's 

### ISSUE THREAD

**Issue by escservices** [dietah/nut-http#2]
Hi! 

This project is awesome and has been a big help to me so far.  I ran into a small issue and I was just curious if you've run into something similar or if you have any suggestions.

Your API is detecting and reporting on both my UPS's and telegraf is able to get take that data in using the inputs.http but only for one UPS at a time. 

For example, if I have 1 inputs.http config setup in telegraf it works fine, when I add the second one telegraf throws the error below (Internal Server Error 500). 

`[inputs.http] Error in plugin: [url=http://192.168.1.29:3001/devices/ups2?parsed=true]: received status code 500 (Internal Server Error), expected any value out of [200]`

I checked the log for your docker and it occasionally throws the following error.
 
`[ERROR] nut-http - Other communication still running`
 
I have a feeling it's because telegraf is querying the API for both UPS's at the same time.  Have you ever ran into this or do you have any ideas on how I might be able to get it working?

Thanks again!

**Comment by escservices** [comment]
For anyone wondering, I think I resolved it by adding a "collection_jitter" under agent config in my telegraf config.  Basically, it ensures each plugin in telegraf fires at a different time.  My global interval is 15s and I set my collection_jitter to 10s and it's been running for a few minutes with no errors.  

https://docs.influxdata.com/telegraf/v1.15/concepts/glossary/#collection-jitter

**Comment by dietah** [comment]
Hi!

Awesome, I'm happy to hear it is of use to someone! 😊

Regarding the error, I am extending a lib that fetches data via the nut commands. Apparently that protocol is not the fastest and I remember having quite some issues when running it on a Pi in docker and had to append chucks of the stream together to get 1 final result.

So I was going to suggest something like your solution, defining multiple calls but with a delay between them. There doesn't seem to be an option for the http input to set a delay. What you could do is run them at different intervals so they are triggered on different timestamps. However, if that jitter setting is working it looks like a clean solution.

Thanks!

**Comment by dietah** [comment]
Hi @escservices ,

I was intrigued by your issue and I have released an updated version where I introduced a LOCK timeout for when a call is triggered at the exact same moment. The timeout is set default to 1000ms but you can adjust if necessary.

This way you should be able to remove the jitter setting from Telegraf.

**Comment by escservices** [comment]
Thanks!  I'll give it a shot, the jitter works well but I also want to use your api for other things and this will probably help everything run smoothly.
