### ISSUE TITLE
Expose the user/password as environment variables

### ISSUE THREAD

**Issue by juchong** [dietah/nut-http#4]
Hi! Do you think it would be possible to have you expose the user/password as environment variables? Thanks!

**Comment by dietah** [comment]
Hi!

Thank you for your interest in my little project.
I have added these but could not test the functionality myself.

**Comment by juchong** [comment]
lol thank YOU for making the software open-source! Let me give it a try.

**Comment by dietah** [comment]
Added functionality in a25e28a143b019c836e9c568abf095cf2a61741e
