### ISSUE TITLE
Getting "nut encountered an error: Error [ERR_SOCKET_CLOSED]: Socket is closed"

### ISSUE THREAD

**Issue by kformosa** [dietah/nut-http#5]
I have a UPS connected to my Proxmox machine and I have set up NUT as a netserver. All configs are done and working both on the local machine and can be reached from an other machine over port 3943 using "upsc ups@192.168.1.4"

I first tried to spin your docket image and when I hit the endpoint on 3001/devices I got that error. I thought that it was due to docker not forwarding "external" traffic.

However I than spinned a new machine on Linode. I have checked connection to the upsd from there by installing nut-client, and worked fine. I cloned your repo, changed the IP and credentials and started the server. However when I hit /devices, I am again getting the same error. 

Server log:
```
root@localhost:~/projects/nut-http# npm start

> nut-http@1.1.0 start
> node index.js

[2021-09-23T10:28:32.331] [INFO] nut-http - environment variables:
 {
  LOG_LEVEL: 'DEBUG',
  SERVER_PORT: 3001,
  SERVER_TIMEOUT: 120000,
  NUT_ADDRESS: 'x.x.x.x',
  NUT_PORT: 3493,
  NUT_USERNAME: '[REDACTED]',
  NUT_PASSWORD: '[REDACTED]',
  LOCK_TIMEOUT: 1000
}
(node:3365) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2021-09-23T10:28:32.355] [INFO] nut-http - nut-http listening on port 3001
[2021-09-23T10:29:34.995] [DEBUG] nut-http - received LIST /devices
[2021-09-23T10:29:34.999] [ERROR] nut-http - nut encountered an error: Error [ERR_SOCKET_CLOSED]: Socket is closed
    at new NodeError (node:internal/errors:371:5)
    at Socket._writeGeneric (node:net:770:8)
    at Socket._write (node:net:792:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Nut.send (/root/projects/nut-http/node-nut.js:77:26)
    at /root/projects/nut-http/node-nut.js:449:18
    at /root/projects/nut-http/node-nut.js:96:17
    at new Promise (<anonymous>) {
  code: 'ERR_SOCKET_CLOSED'
}
[2021-09-23T10:29:35.003] [ERROR] nut-http - Other communication still running
```

Client log:
```
C:\Users\KFormosa>curl http://y.y.y.y:3001/devices
{"code":500,"message":"an internal error occurred Other communication still running"}
```

I confirmed with nmap that port 3493 on my Proxmox machine is open (ofc otherwise upsc wouldn't have worked).

Output from upsc running on the Linode machine (where the NodeJS is running):
```
root@localhost:~/projects/nut-http# upsc ups@x.x.x.x
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 20
battery.mfr.date: CPS
battery.runtime: 1440
battery.runtime.low: 300
battery.type: PbAcid
battery.voltage: 13.2
battery.voltage.nominal: 12
device.mfr: CPS
device.model: VP1000ELCD
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.data: CyberPower HID 0.4
driver.version.internal: 0.41
input.transfer.high: 295
input.transfer.low: 167
input.voltage: 230.0
input.voltage.nominal: 230
output.voltage: 230.0
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.delay.start: 30
ups.load: 22
ups.mfr: CPS
ups.model: VP1000ELCD
ups.productid: 0501
ups.realpower.nominal: 550
ups.status: OL
ups.test.result: No test initiated
ups.timer.shutdown: -60
ups.timer.start: -60
ups.vendorid: 0764
```

I am at a loss why I'm getting these issues.

**Comment by kformosa** [comment]
I do hope you are still maintaining this project - it is exactly what I need in order to create and update an Entity in HomeAssistant from the returned JSON payload.

**Comment by dietah** [comment]
Hi,

I'm still "maintaining" the project but don't have a lot of time at the moment.

Are you using a password and username to protect NUT itself? If so, could you try without, since that was the last code I added and did not really test it myself.

Since you are running it directly without docker, you could also checkout the previous commit before I added that code: 7a052428c22948d150ae93a6cbc75eeb927647d7

**Comment by alexlo0** [comment]
Hi @dietah,

Just to confirm this issue with username/password applied. Also I've checked the previous commit you mentioned - it works like a sharm.

**Comment by dietah** [comment]
I reverted the username and password changes in v1.2.2.
As I don't use these myself I cannot easily test them.
