### ISSUE TITLE
LOG_LEVEL environment var DON'T work

### ISSUE THREAD

**Issue by alexlo0** [dietah/nut-http#7]
As of initial settings in env.js log files are obviously set to DEBUG level. But, if you try to set up another log level via env variables (or even inside env.js) doesn't work as expected. The log level remains the same as debug. Also I've investigated, that changing level other than debug inside logger.js (line #14) works out. Please check it out.

**Comment by dietah** [comment]
Good catch, never noticed it.

Fixed in v1.2.2
